FROM alpine:edge

ENV version=0.38
ENV UID=10000
ENV GID=10000

VOLUME ["/etc/motioneye", "/var/lib/motioneye"]
COPY entrypoint.sh /entrypoint.sh

##RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories\
RUN  apk --no-cache add\
    bash\
    motion\
    py2-pip\
    python\
    curl\
    tzdata\
&&  apk --no-cache add --virtual=buildreq\
    build-base\
    jpeg-dev\
    openssl-dev\
    python-dev\
    zlib-dev\
&&  pip install motioneye==$version\
&&  apk del buildreq\
&&  test -e /etc/motioneye/motioneye.conf || cp /usr/share/motioneye/extra/motioneye.conf.sample /etc/motioneye/motioneye.conf\
&&  addgroup -g 10000 motioneye && adduser -u 10000 -G motioneye -D motioneye && chmod 775 /run /var/log && chown motioneye.motioneye /run /var/log


CMD /usr/bin/meyectl startserver -c /etc/motioneye/motioneye.conf

EXPOSE 8765



#&&  chmod +x /entrypoint.sh && chmod 775 /run /var/log && chown motioneye.motioneye /run /var/log
